### ISSUE TITLE
Update custom DSi/3DS skins page for TWiLight Menu++ v25.8.0

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/twlmenu-extras#129]
The following items need to be added/adjusted in the DSi/3DS skins page:
- [ ] Custom color palette support for user profile-colored elements ([#2137](https://github.com/DS-Homebrew/TWiLightMenu/pull/2137))
  - Likely needs a whole section. See pull request for detailed information
- [ ] `DarkLoading` theme.ini setting ([#2134](https://github.com/DS-Homebrew/TWiLightMenu/issues/2134))
- [ ] `UseAlphaBlend` theme.ini setting ([#2141](https://github.com/DS-Homebrew/TWiLightMenu/pull/2141))
  - Additional information/description on this?

**Comment by DieGo367** [comment]
`ProgressBarColor` is another new theme.ini setting. It controls the color of the progress bar if `ProgressBarUserPalette` is turned off.

**Comment by spellboundtriangle** [comment]
Apparently I opened this on the wrong repository, would someone mind moving it to [wiki](https://github.com/DS-Homebrew/wiki)? Thanks
